name: Bug Report
description: File a bug report to help us improve
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of laag are you using?
      placeholder: e.g., 2.0.0
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - '@laag/core'
        - '@laag/openapi'
        - '@laag/raml'
        - '@laag/smithy'
        - 'Multiple packages'
        - 'Not sure'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import the package...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g., macOS, Windows, Linux]
        - Node.js version: [e.g., 18.17.0]
        - Package manager: [e.g., npm, yarn, bun]
        - TypeScript version: [e.g., 5.0.0]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including logs or screenshots
